# https://levelup.gitconnected.com/create-pipeline-to-push-docker-image-to-ecr-deploy-containerised-app-to-elastic-beanstalk-e721af796f33
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  build:
    commands:
      #   - echo Build started on `date`
      #   - echo Building Docker test image...
      #   - docker build -t my_portfolio:latest -f Dockerfile.dev .
      #   - docker run -e CI=true my_portfolio:latest npm run test
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my_portfolio:latest .
      - docker tag my_portfolio:latest 825318865272.dkr.ecr.ap-southeast-2.amazonaws.com/my_portfolio:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 825318865272.dkr.ecr.ap-southeast-2.amazonaws.com/my_portfolio:latest

artifacts:
  files:
    - "**/*"
  discard-paths: no
